### PR TITLE
Add support for more exotic speed dial folder constellations

### PR DESCRIPTION
**Pull request by cB-Abhinav-Gautam**
1. Folder inside folder
2. Multiple speed dial folders
3. Thumbnail not appearing for new speeddials

### CODE REVIEW

**Comment by lagru** [comment]
Hey, thank you for your fast contribution. I'll try out and test this over the next few days. 

At a quick glance I noticed the following things:
- The docstring in `recurser` is a bit messed up and could be a little bit more descriptive for a function with this much responsibility.

**Comment by lagru** [comment]
Related to #5

**Comment by cB-Abhinav-Gautam** [comment]
👍

**Comment by lagru** [comment]
Hey @Gotham13121997, I intend to archive / delete this repository in a couple of days as its content is no longer up-to-date and I don't intend to continue working on this. 

Therefore I won't merge this PR. However I still want to thank you for the time & work you took while creating this PR and hope that this doesn't leave a bad feeling. :slightly_smiling_face:

**Comment by cB-Abhinav-Gautam** [comment]
Its fine 👍

**Comment by lagru** [comment]
I'm happy to hear that!

**Pull request closed without merging**
